--------------------------------------------------------
--  File created - Thursday-July-13-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GATEWAY_PARAMETER_CHANNEL
--------------------------------------------------------

  CREATE TABLE "SOA_APP"."GATEWAY_PARAMETER_CHANNEL" 
   (	"PAYMENT_TYPE" VARCHAR2(250 CHAR),
  "SYSTEM_ID_OR_MCP_ID" VARCHAR2(50 CHAR), 
	"TRANS_CODE" VARCHAR2(20 CHAR), 
	"CREATED_AT" TIMESTAMP (6), 
	"IS_USING_PROXY" NUMBER(1,0), 
	"PROXY_IP" VARCHAR2(20 CHAR), 
	"PROXY_PORT" VARCHAR2(10 CHAR), 
	"UPDATED_AT" TIMESTAMP (6), 
	"URL" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_WSRR" ;
--------------------------------------------------------
--  DDL for Index GATEWAY_PARAMETER_CHANNEL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOA_APP"."GATEWAY_PARAMETER_CHANNEL_PK" ON "SOA_APP"."GATEWAY_PARAMETER_CHANNEL" ("PAYMENT_TYPE","SYSTEM_ID_OR_MCP_ID", "TRANS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_WSRR" ;
--------------------------------------------------------
--  Constraints for Table GATEWAY_PARAMETER_CHANNEL
--------------------------------------------------------

  ALTER TABLE "SOA_APP"."GATEWAY_PARAMETER_CHANNEL" MODIFY ("PAYMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SOA_APP"."GATEWAY_PARAMETER_CHANNEL" MODIFY ("SYSTEM_ID_OR_MCP_ID" NOT NULL ENABLE);
  ALTER TABLE "SOA_APP"."GATEWAY_PARAMETER_CHANNEL" MODIFY ("TRANS_CODE" NOT NULL ENABLE);
  ALTER TABLE "SOA_APP"."GATEWAY_PARAMETER_CHANNEL" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SOA_APP"."GATEWAY_PARAMETER_CHANNEL" MODIFY ("IS_USING_PROXY" NOT NULL ENABLE);
  ALTER TABLE "SOA_APP"."GATEWAY_PARAMETER_CHANNEL" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SOA_APP"."GATEWAY_PARAMETER_CHANNEL" ADD CONSTRAINT "GATEWAY_PARAMETER_CHANNEL_PK" PRIMARY KEY ("PAYMENT_TYPE","SYSTEM_ID_OR_MCP_ID", "TRANS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_WSRR"  ENABLE;
