--1. Tambah kolom

ALTER TABLE gateway_parameter_channel add PAYMENT_TYPE VARCHAR2(50);

--2. Update data null

UPDATE gateway_parameter_channel set PAYMENT_TYPE='-' WHERE PAYMENT_TYPE IS NULL;

--3. Select Constraint Name dan Constraint Type untuk mengetahui constraint primary key table (Constraint_type = p)

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'GATEWAY_PARAMETER_CHANNEL';

--4. Select Index_name table

SELECT INDEX_NAME FROM USER_INDEXES WHERE TABLE_NAME = 'GATEWAY_PARAMETER_CHANNEL';

--5. Hapus sementara dan recreate constraint /index 

ALTER TABLE gateway_parameter_channel DROP CONSTRAINT SYS_C0011835;

DROP INDEX SYS_C0011835;

--6. Create Unique Index

CREATE UNIQUE INDEX "SOA_APP"."GATEWAY_PARAMETER_CHANNEL_PK" ON "SOA_APP"."GATEWAY_PARAMETER_CHANNEL" ("PAYMENT_TYPE", "SYSTEM_ID_OR_MCP_ID", "TRANS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_WSRR";

--7. Add Constraints Table

ALTER TABLE "SOA_APP"."GATEWAY_PARAMETER_CHANNEL" ADD CONSTRAINT "GATEWAY_PARAMETER_CHANNEL_PK" PRIMARY KEY ("PAYMENT_TYPE", "SYSTEM_ID_OR_MCP_ID", "TRANS_CODE");
